# Generated by Django 4.2.18 on 2025-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
