# Generated by Django 4.2.18 on 2025-01-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
